### ISSUE TITLE
StarryPy3k is running, but players are unable to connect

### ISSUE THREAD

**Issue by ghost** [kharidiron/StarryPy3k#1]
Thanks a lot for keeping this tool updated!

I tried running StarryPy3k on my server. It seemed StarryPy3k did launch, but whenever one of my character tries connecting to it, it shows "Joine failed" No server response" on Starbound client.

Here're logs of starbound_server and StarryPy3k.
(starbound_server log)
http://pastebin.com/paQ8YMut

(StarryPy3k log)
http://pastebin.com/d2tF4ser

(Misc. information)
Server IP:192.168.10.200
Client IP:192.168.10.100

Server OS: Ubuntu server 16.04 LTS
Python version: 3.5.2

Starbound server version: Unstable, release date 2016/7/20

**Comment by kharidiron** [comment]
I'm working to try and replicate this now. The main question is, have you updated your config.json to point to the right server/port combo for your server?

**Comment by ghost** [comment]
> have you updated your config.json to point to the right server/port combo for your server?

I used the default config.json which was cloned to config directory. I have edited starbound_server.config so that I have the port 31025 as the game port.

**Comment by kharidiron** [comment]
oop.... my version of starbound nightly is a little old. updating to the newest version... and it looks like they might have made some more packet changes I wasn't aware of... ~_~

**Comment by kharidiron** [comment]
Okay, this is going to take some time to sort out. Upstream changed the packet ordering, as well as some of the packet contents, in the Unstable build. I hadn't been working with unstable up until now, so I hadn't see these changes. Doh...

**Comment by ghost** [comment]
Thanks for the update! I'll gladly wait then~

**Comment by kharidiron** [comment]
Ok, try running 669e941 when you get the chance.

**Comment by ghost** [comment]
It's working, a job nicely done!
I'll keep it running to see if anything funny happens.
