### ISSUE TITLE
Claims

### ISSUE THREAD

**Issue by kharidiron** [kharidiron/StarryPy3k#10]
Let users claim a planet for building.

Should tie into the planet protect system.

This will require a bit of work, so pushing it off for now.

**Comment by davoodinator** [comment]
how is this different than /protect ? will it be for planets not visited yet? like claiming a star system for example?

**Comment by kharidiron** [comment]
With planet protect, only admins+ can protect a planet. With claims, any player can claim (a limited number of) planets, as their own. It ties into planet protect, but makes it so admins don't have to be available at all times to beam over and apply protection.

This is already implemented in the old starrypy, and a lot of people used it; hence the desire to port it over to SP3k.

**Comment by davoodinator** [comment]
is it possible to do a filtering of actions available for protection via config.json.  the original StarryPy had something like that setup
[config.json.default.txt](https://github.com/kharidiron/StarryPy3k/files/390527/config.json.default.txt)

id like my players to protect against building and opening containers, but not from harvesting or interacting with objects and doors.

if possible. it would be nice to be able to differentiate between types of containers. but that might be a bit too much work
