### ISSUE TITLE
Name sanitization

### ISSUE THREAD

**Issue by Tsunder** [kharidiron/StarryPy3k#18]
Sanitize player names always/upon join and when using /nick

remove coloring ^.*;
remove duplicate spaces
remove special/typeable characters (Limit to alphanumeric?)
maybe truncate name length

**Comment by kharidiron** [comment]
Commit 8904c1d8652956df2a6876f682e5ed1da5e71856 adds colored name sanitation.

Simple regex that matches on all `^****;` type values, and removes them. Works for `^#hex;`, `^color name;` and `^fades, shadows, etc...;`

**Comment by rubellyte** [comment]
Name sanitizing doesn't apply to the /nick command.

**Comment by kharidiron** [comment]
PR #29 makes some fixes to this.

**Comment by kharidiron** [comment]
Handled in PR #33. Closing issue.
