### ISSUE TITLE
How can I enable StarryPy3k's admin command such as /kick? 

### ISSUE THREAD

**Issue by ghost** [kharidiron/StarryPy3k#2]
Hello,

The latest commit seems running so far, but my owner character can not use /kick command.
The debug.log reads as follows: 
`2016-07-20 15:54:31,577 - ERROR - starrypy.plugin.command_dispatcher # Unknown exception encountered. Ignoring.
Traceback (most recent call last):
  File "/home/usiemon/StarryPy3k/plugins/command_dispatcher.py", line 131, in run_command
    connection)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
    res = yield from res
  File "/home/usiemon/StarryPy3k/plugins/player_manager.py", line 763, in _kick
    if not p.logged_in:
AttributeError: 'NoneType' object has no attribute 'logged_in'`

I guess I must add a Starbound server user like we do in the plain StarryPy, but what name should that user have?

**Comment by kharidiron** [comment]
Issue _somewhat_ resolved in 41c12a1... in that, you can now kick a person. On the other hand, it still causes their client to crash when you do so. Still can't seem to figure this one out. It looks like it might have something to do with some additional context information being passed to the client just before the kick takes place... but to be honest, I'm not certain.

**Comment by ghost** [comment]
Thanks for a quick move!

Now I can at least use /kick. The client-side crash is also reproduced. I noticed another issue regarding to this, so I will make a new issue!
