### ISSUE TITLE
Planet Protect Plugin

### ISSUE THREAD

**Issue by kharidiron** [kharidiron/StarryPy3k#20]
While planet protect is already in and working, the setting on it is a bit restrictive; it blocks all on_entity_interact packets. This leads to people not being able to sit in chairs, use teleporters, open doors, etc.

**Comment by ghost** [comment]
I had a report that those not on the protect list goes invisible when they beam in to a protected planet.

I will check if this still happens with the latest commit!

**Comment by davoodinator** [comment]
yeah it was happening on ships too.

**Comment by kharidiron** [comment]
I've implemented this in my latest commit, though it now needs much more extensive testing to be certain it is working as expected.

**Comment by rubellyte** [comment]
Planet Protect does not protect breakables, or prevent the removal of moving platforms.

**Comment by kharidiron** [comment]
This is working as well as can be hoped... though I'm not marking it complete as I'm sure more fixes will be needed on it, and I'd like to try and see if breakables can be handled somehow.

**Comment by kharidiron** [comment]
Fixes in commit https://github.com/kharidiron/StarryPy3k/commit/8d48590de29313b4c8c8f3f3e5e81e004ee45b74 to prevent item loss under certain circumstances.

Can't prevent item loss from placing tiles, currently. May not be able to, ever, since the tile brush system is a bit too complex. These fixes, at least, should make this protect mechanism a lot more acceptable.

**Comment by kharidiron** [comment]
At this juncture, I'm calling this done. Further corrections and enhancements can go in a new issue.
