### ISSUE TITLE
Planet protection won't save when StarryPy3k quits

### ISSUE THREAD

**Issue by ghost** [kharidiron/StarryPy3k#22]
Hi,

It seems like what we do with /protect command won't save when StarryPy3k quits.
The last night we protected a few ships and planets and added a few players to their builder list. After restarting both StarryPy3k and Starbound, all the protection were gone.

**Comment by kharidiron** [comment]
I'm not able to reproduce this: I've got a protected planet that maintains its protected status between restarts of StarryPy.

**Comment by ghost** [comment]
So far I couldn't reproduce this either. I guess we can close this issue for now.

**Comment by ghost** [comment]
Just a quick word to bring this issue up once more.

It seems to have happened again. The log shows no sign of "Config file saved." before StarryPy3k quit, but several lines of errors. 

I'll dig my syslog to see if there's any clues.

Edit: The syslog shows the systemd service(which I wrote for StarryPy3k) entered a failed state with core-dump. I'll try running it as a non-service to see if there'd be any difference.

**Comment by kharidiron** [comment]
Is this still an occurring issue?

**Comment by ghost** [comment]
Yes, though it is quite random. It happens when StarryPy3k fails to save
while quitting.

2016/09/09 午後2:41 "kharidiron" notifications@github.com:

Is this still an occurring issue?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
https://github.com/kharidiron/StarryPy3k/issues/22#issuecomment-245824272,
or mute the thread

**Comment by kharidiron** [comment]
I'm going to mark this as closed for two reasons; 1) it seems to be isolated, as I have yet to be able to reproduce the issue. and 2) I plan to change over part of the backed system (the player db) which can also be used to store other useful tables as well (like planet protects). This should resolve issues with saving.
