### ISSUE TITLE
StarryPy3k's RAM usage with Starbound 1.0.3

### ISSUE THREAD

**Issue by ghost** [kharidiron/StarryPy3k#24]
Hi,

It appears StarryPy3k's RAM usage has risen again since Starbound 1.0.3 hit. It is not as severe as before, but I saw python3 was using up 1.0 GByte of RAM after 3 hours of operation. During that operation, StarryPy3k logged almost 200 connections received and 60 errors. 

As a side note, the server has been having a minor connection hiccups since Starbound 1.0.3. I am not sure if this is due to either StarryPy3k or Starbound. Starbound itself is eating up to 8 GByte of RAM after 3 hours of operation, with almost 30 logged errors.

**Comment by kharidiron** [comment]
Are you still seeing the increased RAM usage? I am not seeing this on my server, as far as I am aware...

**Comment by ghost** [comment]
Nope, the issue seems to have resolved with the latest commit. 4 hours of operation with 60 connection received, and it used less than 300 MBytes of RAM.

Thank you for the fix!
