### ISSUE TITLE
IRC chat relay is not sent in-game emotes (/me dances)

### ISSUE THREAD

**Issue by dopeghoti** [kharidiron/StarryPy3k#36]
If one plugin can loop into another, the general in-game chat plugin that catches emotes should check to see if `irc_bot` is active, and if so, send a mock chat message to the relay that emulates in-game actions/emotes.

**Comment by kharidiron** [comment]
How do you like them apples :3. https://github.com/kharidiron/StarryPy3k/commit/7305b8cd44895b35c8e5e438259dbe3acccd7032

**Comment by dopeghoti** [comment]
They're delicious.
