### ISSUE TITLE
Add "maintenance" mode - reject new player connections

### ISSUE THREAD

**Issue by dopeghoti** [kharidiron/StarryPy3k#38]
I prefer not to kick players off of my server if I don't have to, just to upgrade Starbound or the proxy.

It would be helpful to add an owner or admin command to tell StarryPy to no longer accept new player connections until either told otherwise or it is restarted.  That way, server admins can flip this switch, and when the last connected players leave of their own volition, the service(s) can be updated and restarted.

Bonus points for either or both of giving a configurable message shown to rejected clients, or for managing the MOTD and in-game broadcasts.

**Comment by kharidiron** [comment]
This is not an immediately-easy thing to implement well. I'm going to put it off for how, but I'll keep it in the queue.

**Comment by ren-kun** [comment]
Perhaps instead, you make a maintenance mode for a planet? This could tie into planet protection. 

In essence you could block access to a world you need to work on (Perhaps a spawn or hub) and players can still connect and do their own thing.

**Comment by kharidiron** [comment]
This issue was moved to StarryPy/StarryPy3k#37
