### ISSUE TITLE
Chat censoring

### ISSUE THREAD

**Issue by ren-kun** [kharidiron/StarryPy3k#40]
If possible, have a dictionary that will check chat for cussing or rude words.

No more need to patrol chat for cussing etc. 

Also allow the plugin to reload when adding new dictionary words on the fly.

**Comment by dopeghoti** [comment]
On-the-fly dictionary reload ties into Issue #35 nicely.

**Comment by kharidiron** [comment]
This issue was moved to StarryPy/StarryPy3k#36
