### ISSUE TITLE
Protecting Instance worlds.

### ISSUE THREAD

**Issue by ren-kun** [kharidiron/StarryPy3k#46]
I would like to protect my custom instance worlds and things like the outpost.

People are going nuts on it and crashing the server with an immense amounts of items on the floor.

**Comment by ren-kun** [comment]
After thinking, I would like to have toggle options for things like..

"Allow dropped items"
"Delete items on drop"
"Allow use/interaction with items"

**Comment by kharidiron** [comment]
This issue was moved to StarryPy/StarryPy3k#35
