### ISSUE TITLE
Can not kick a player who DCed - and can not connect after

### ISSUE THREAD

**Issue by ren-kun** [kharidiron/StarryPy3k#47]
So a user crashes or the game kicks them out for what ever reason.

They then can't log back in as the error is along the lines of "As user is logged in already"

Can't not kick the player and the command doesn't reply either. 

Reap time set to 1

**Comment by kharidiron** [comment]
For the time being, I'm going to mark this as 'will not fix' because I plan to gut and rewrite the player management system. Hopefully, with switching back to an SQL basis, it will be a lot easier to deal with this weird issues.
