### ISSUE TITLE
Party Chat

### ISSUE THREAD

**Issue by kharidiron** [kharidiron/StarryPy3k#7]
Allow members of the same party to talk privately with each other.

**Comment by kharidiron** [comment]
I have this practically done and ready for 1.0... The problem is, the client_context_update packet is behaving erratically and causes the StarryPy server to deadlock.

I'm currently at a bit of a loss on how to fix this issue, which is why it has been moved to post-1.0

**Comment by kharidiron** [comment]
I'm really hoping 1cc55e27458f862593643cc779a48870cedbaa50 may have fixed some of the issues I was having with this enhancement. I will have to test this later.

**Comment by rubellyte** [comment]
Party chat (and local chat) are now implemented in Starbound as of 1.1, we can close this.

**Comment by kharidiron** [comment]
6d3123b handles this. I was able to hook the starbound implementation of party chat, so we now have a convenience command of `/p` that we can use.
